### ISSUE TITLE
[ZipArchive] Prefix issue under windows

### ISSUE THREAD

**Issue by Tofandel** [thephpleague/flysystem#1528] opened 2022-08-03 21:35 UTC
### Bug Report

I'm reopening https://github.com/thephpleague/flysystem-ziparchive/issues/20 here as that's a subsplit and not monitored (maybe consider removing the PR section and issues of the git project)

This is a follow up after some digging up of https://github.com/pierrejoye/php_zip/issues/32

This package adds a `/` prefix (leading slash) to all files it adds to the archive https://github.com/thephpleague/flysystem-ziparchive/blob/3.x/ZipArchiveAdapter.php#L51

This is not valid according to the [zip specs](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) this creates an issue where the zip content is not visible in the windows zip explorer

>    4.4.17 file name: (Variable)
> 
>        4.4.17.1 The name of the file, with optional relative path.
>        The path stored MUST NOT contain a drive or
>        device letter, or a leading slash.  All slashes
>        MUST be forward slashes '/' as opposed to
>        backwards slashes '\' for compatibility with Amiga
>        and UNIX file systems etc.  If input came from standard
>        input, there is no file name field.  
> 

This effectively makes the ZipArchiveAdapter unusable as it does not create a valid zip file

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.2.0

#### How to reproduce

Use ZIpArchive to create an archive
Open the created Zip file, it will be empty in the Windows explorer

**Comment by Matth--** [comment] 2022-08-05 08:37
Same issues when trying to use `listContents('', true) with a zip that got downloaded somewhere. The unit tests seem to only cover leading slashes when creating and reading from a zip folder.

**Comment by PhilETaylor** [comment] 2022-08-14 09:01
I can confirm this bug. To replicate on a Mac just right click a file in finder and select "Compress", the resulting zip file when read with listContents produces a blank array. 

downgrading to 3.1.1 fixes the issue for me for now, 3.2.0 is unusable in production because of this.

**Comment by frankdejonge** [comment] 2022-08-14 10:16
Almost back from holiday, will attend to after.

**Comment by PhilETaylor** [comment] 2022-08-14 10:17
Holidays are important, absolutely no pressure for a fix for me (I just downgraded for now)! Don't feel any pressure at all please !

**Comment by frankdejonge** [comment] 2022-08-14 20:51
Version 3.2.1 was just released to address this, if it's fixed for you, please close the issue 🙏

**Comment by PhilETaylor** [comment] 2022-08-15 09:27
I can confirm that 3.2.1 has fixed the issue I was having.

**Comment by frankdejonge** [comment] 2022-08-15 11:14
👍

**Closed as completed by frankdejonge** 2022-08-15 11:14 UTC

**Comment by PhilETaylor** [comment] 2022-08-15 11:16
Thank you! 🚀

**Comment by Matth--** [comment] 2022-08-15 12:23
@frankdejonge 

I don't think that reverting that commit fixes this issue. The initial issue was that creating a zip archive adds a prefixed slash. Opening those archives with windows will probably break (Can't really test as I have no windows machine atm). 

The PR I opened should have resolved this issue as it strips leading slashes. Will update my pr tomorrow as I'm away from my laptop at the moment. 

I think we could re-open this issue (?)

**Comment by PhilETaylor** [comment] 2022-08-15 12:25
To be clear. I have tested in a ubuntu docker container, code that used to work that was broken, and 3.2.1 fixed that for me. This is for both zips created on ubuntu and zips created on a Mac in finder (right click, compress). I too have no access for to a windows machine.
