### ISSUE TITLE
Request: Google Drive

### ISSUE THREAD

**Issue by benjam-es** [thephpleague/flysystem#192] opened 2014-06-28 14:30 UTC
Would it be worth adding google drive as an option?

**Comment by sagikazarmark** [comment] 2015-01-24 20:53
Any progress?

**Comment by JC5** [comment] 2015-02-03 20:30
The Google Storage API is very similar to the Google Drive API. Might be something to consider.

**Comment by jabbon** [comment] 2015-02-13 14:39
I would be nice support for Google Cloud Storage +1

**Comment by bogdanghervan** [comment] 2015-03-14 03:56
+1 for a Google Cloud Storage adapter.

**Comment by sagikazarmark** [comment] 2015-03-14 20:07
Make no mistake: Google Cloud Storage is not the same as Google Drive. (And the issue is about Google Drive)

**Comment by bogdanghervan** [comment] 2015-03-14 20:13
No mistake made. In fact I went ahead and added a separate issue for GCS, #448.

**Comment by sagikazarmark** [comment] 2015-03-14 20:19
Great, you are not the first mentioning GCS instead of GD.

**Comment by alimuzaffarkhan** [comment] 2015-03-20 05:17
I haven't read the Google Drive API yet but Google Drive doesn't do anything special than any other Unix/Linux based system. We can have Files with same names in different folders on any filesystem as well, also we can have same file in multiple folders using links.

**Comment by Garbee** [comment] 2015-03-20 08:49
It isn't anything like traversing a Linux system. That is a gross
understatement of what is required.

**Comment by dimaip** [comment] 2015-05-12 14:02
Any updates on Google Drive support?

**Comment by matthewbaggett** [comment] 2015-05-12 14:03
You're not the only one waiting out with wishful hopes for Google Drive
support.

- Matthew Baggett

Add me on Linked In <http://uk.linkedin.com/pub/matthew-baggett/1b/8a2/378> or
Twitter <http://twitter.com/matthewbaggett>!
You can always find the most up-to-date version of my CV on Google Drive
<https://docs.google.com/document/d/1Qu4CxPaScmBwOjuNdz8Wv-6ZfwYQUpEriZ8Kojniq6E/edit?usp=sharing>
or
view my GitHub <https://github.com/matthewbaggett>.
Skype: matthewbaggett
Or call me: 07541 059 344

**Comment by alexw23** [comment] 2015-05-22 04:15
:+1:

**Comment by fbm-static** [comment] 2015-06-04 12:29
:+1: Woot woot!

**Comment by alexw23** [comment] 2015-06-16 07:48
After fiddling around a little I found that the Google Drive API follows suit with `Box` and `OneDrive`, so I actually think the abstraction layer needs to be thought out and improved to support these standards, through a library of some sort. There needs to be more traversal implementations to handle these in a consistent manner.

I disagree with the issue of multiple http calls as really the GDrive API is super quick and most file system tasks are happening in the backend anyway so they are not time sensitive.

**Comment by alexw23** [comment] 2015-06-16 08:19
I've uploaded my hacky implementation here - looking for collaborators to help continue this
https://github.com/ignited/flysystem-google-drive

**Comment by nojacko** [comment] 2015-06-26 12:12
Nice one @alexw23. If I get any spare time I'll try to help out. Really want this one.

**Comment by asivaneswaran** [comment] 2015-07-27 14:27
Hey guys, any news on this?

**Comment by alexw23** [comment] 2015-07-28 08:48
Still looking for help on https://github.com/ignited/flysystem-google-drive

**Comment by JayBizzle** [comment] 2015-07-28 13:59
@alexw23 where do you need help? What's the status of your implementation? Any particular issues?

**Comment by gpilla** [comment] 2015-08-31 18:59
+1

**Comment by gpilla** [comment] 2015-08-31 18:59
@alexw23 I also offer my help...

**Comment by alexw23** [comment] 2015-08-31 22:26
See https://github.com/ignited/flysystem-google-drive/issues/1

**Comment by raydric** [comment] 2015-10-06 19:48
I guess this is not happening? I would contribute but my PHP/lib knowledge is very limited and the Google API files are a complete mess.

**Comment by frankdejonge** [comment] 2015-10-06 19:49
@raydric I'd love to be able to work with an sdk that made sense for this case, but there isn't which makes this task to big to tackle, as many have tried and unfortunately failed.

**Comment by raydric** [comment] 2015-10-06 19:54
@frankdejonge I understand, thanks anyway! Their documentation is huge (but not complete) and weird. Two hours in and it's already *driving* me crazy.

**Comment by frankdejonge** [comment] 2015-10-06 19:55
@raydric many times have I though about doing this, but I keep getting lost and it's just too frustrating having to go through it.

**Comment by frankdejonge** [comment] 2015-10-06 19:55
In light of this, I'm closing this issue.

**Comment by alexw23** [comment] 2015-10-06 20:36
I've already implemented this and have it working fine. https://github.com/ignited/flysystem-google-drive, we are already using the implemented methods in production and haven't had an issue so far. There is still work to be done on the rest of the methods. (https://github.com/ignited/flysystem-google-drive/issues/1)

**Comment by garygreen** [comment] 2015-10-07 08:36
@frankdejonge I'd recommend to keep it open, at least for others to see there is a desire and have a stab at it.

**Comment by alexw23** [comment] 2015-10-07 09:38
Yeah - if someone wants to submit a PR for any of them methods please do. We can get it wrapped up in no time.

**Comment by touqeershafi** [comment] 2015-12-11 06:33
Any Progress on Google Drive Integration ?

**Comment by wordskill** [comment] 2016-01-26 13:35
I would like to add some recent information that highlights how useful this functionality would be. Of course, that does not make it any easier to implement but does suggest that the reward might be worth the struggle.

Until recently, Google Apps for Work (at $10 per month) only gave unlimited storage to organizations with 5 or more users, anyone with 4 or less users was capped at 1TB.

Now that 1TB cap appears to have been unofficially removed and **even single-user accounts like mine have been given unlimited storage**. I am already using my Google Drive to permanently archive a massive number of website and system backups without any problems at all.

As seven million businesses already use Google Apps for their custom domain email addresses and other apps, it seems likely that some would prefer to use this **free unlimited storage** rather than paid S3 storage or limited Dropbox storage.

In non-first world countries, the price of the 30GB Apps for Work tier has been **reduced from $5 to $3**. This aggressive and highly-targeted pricing suggests that Google is deadly serious about dominating the paid storage market worldwide.

Also, all Google accounts are entitled to a free 15GB Google Drive. I don't know how many Google accounts exist but there are roughly a billion Gmail accounts.

**Comment by nao-pon** [comment] 2016-02-06 16:55
I'm doing work in progress in https://github.com/nao-pon/flysystem-google-drive .

**Comment by progsmile** [comment] 2016-03-28 15:55
:+1:

**Closed** 2016-06-03 18:35 UTC
Labels: enhancement
