### ISSUE TITLE
Race condition in Adapter\Local->createDir()

### ISSUE THREAD

**Issue by Daeroni** [thephpleague/flysystem#1058] opened 2019-08-20 14:11 UTC
### Bug Report

There is a race condition in `Adapter\Local->createDir()`: https://github.com/thephpleague/flysystem/blob/36f1ab08462e8239b616fd3828ace2a78d3a7cbe/src/Adapter/Local.php#L376

If the directory was created between the `!is_dir`-check, and the `mkdir`, it will fail.

One way of handling this would be to just suppress the errors from `mkdir` and disregard its return value, and check again if the directory exists:

```
if ( ! is_dir($location)) {
    @mkdir($location, $this->permissionMap['dir'][$visibility], true)) {
    if ( ! is_dir($location)) {
        return false;
    }
}
```

**Comment by rulatir** [comment] 2019-08-23 17:24
Looks like duplicate of #690 which was closed with a dubious claim that it had been "already implemented in 2016".

**Closed** 2019-08-23 21:33 UTC
