### ISSUE TITLE
"ErrorException" mkdir(): No such file or directory

### ISSUE THREAD

**Issue by FashionCStar** [thephpleague/flysystem#1189] opened 2020-08-28 16:17 UTC
### Bug Report
exception: "ErrorException"
file: "xxxxx\vendor\league\flysystem\src\Adapter\Local.php"
line: 368
message: "mkdir(): No such file or directory"

### This is my code
        $startSec = $this->convertToSec("00:".$request->start);
        $previewThumbName = $request->youtubeId . "-" . $startSec . "-" . rand() . ".png";
        FFMpeg::open("https://www.youtube.com/watch?v=" . $request->youtubeId)
        ->getFrameFromSeconds($startSec)
        ->export()
        ->toDisk('local')
        ->save($previewThumbName);

When I run this code, I am getting above error.
I cant sure what the reason is.

Thanks

**Comment by frankdejonge** [comment] 2020-08-28 16:29
this is not enough information to fix the issue.

**Comment by FashionCStar** [comment] 2020-08-28 16:50
Which information do you need to fix it ?
What should I share with you ?

**Comment by frankdejonge** [comment] 2020-09-06 14:23
First of all, you removed the issue template. It is there for a reason. I have no way to reproduce your bug because the code you share has nothing to do with Flysystem. Try to put yourself in my shoes and think about how you would be able to uncover anything to solve this issue.

I'm closing this issue. If you still have the issue, feel free to open a new issue with more relevant information.

**Closed as completed by frankdejonge** 2020-09-06 14:23 UTC
