### ISSUE TITLE
[S3 Adapter] how to write objects when ACL is not accepted?

### ISSUE THREAD

**Issue by dbaggott** [thephpleague/flysystem#1580] opened 2022-10-25 04:51 UTC
### Question

I'm writing to a bucket that, per AWS' current recommendations, has ACLs disabled on the bucket and uses a Bucket Owner Enforced policy.

When writing to S3, I get an error message indicating:  "The bucket does not allow ACLs"

How does one disable the inclusion of an ACL in the PUT file write request to S3?

Thank you!

**Comment by frankdejonge** [comment] 2022-10-25 06:59
What version are you using?

**Comment by frankdejonge** [comment] 2022-10-25 07:05
I've just created a bucket with ACL disabled and was able to write the file. What operation are you performing and which versions are you using?

**Comment by dbaggott** [comment] 2022-10-25 19:06
Hi @frankdejonge, thank you for the quick reply and apologies for the lack of details.

We only experience the problem if another AWS account owns the bucket.  AWS appears to ignore the ACLs when writing a file using credentials for the account that owns the bucket.

That being said, it appears we're on an ancient version 1.1.4 (Filesystem) and 1.0.29 (flysystem-aws-s3-v3).  So, possibly that is the issue.

Are you in a position to be able to verify that the current version can write files to a Bucket Owner Enforced bucket in another account?

**Comment by frankdejonge** [comment] 2022-10-25 20:10
@dbaggott the upload logic of that package is quite similar to that of the latest. So I doubt that upgrading will fix it. I've locally tested writing to a Bucket Owner Enforced bucket, that had no issues.

**Comment by frankdejonge** [comment] 2022-10-25 20:23
@dbaggott I just installed the exact versions and am also able to write a file, even on the old version. The only thing you need to ensure is not to set the visibility to public. Private works just fine.

**Comment by dbaggott** [comment] 2022-10-25 23:03
@frankdejonge, thanks.  The bucket you're writing to, it's in the same account as the credentials you're using?

**Comment by frankdejonge** [comment] 2022-10-26 18:44
@dbaggott I think I've reproduced your case now. It's when you have another user that should be able to access the bucket but is not the owner. Is that correct?

**Comment by frankdejonge** [comment] 2022-10-26 18:46
Ah no, even then, when using private everything is just fine. I'm at a loss 😅

**Comment by frankdejonge** [comment] 2022-11-14 17:12
Closing due to no further leads.

**Closed as completed by frankdejonge** 2022-11-14 17:12 UTC
Labels: could not reproduce

**Comment by dswansonvizio** [comment] 2023-04-03 22:29
I've been running into this issue all afternoon, using `"laravel/framework": "^9.0"` and `"league/flysystem-aws-s3-v3": "^3.0"`
The bucket would throw the same error as the original poster: 400 Bad Request - AccessControlListNotSupported if I didn't have ACLs turned on and public access allowed even though I was using a bucket policy allowing my cross account role access to the bucket.
I ended up figuring out that getting rid of the ACL was the way around this which makes sense since the bucket I was trying to upload into had ACLs disabled:

`$results = Storage::disk($this->s3_disk)->put($file_path, file_get_contents($file), ['ACL' => '']);`

**Comment by LarsFronius** [comment] 2023-08-10 11:34
AWS these days recommends to keep ACLs disabled in buckets as bucket policies are generally the best way to go about securing access to your objects.
In fact ACLs are by default disabled as of April 5th this year: https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-s3-two-security-best-practices-buckets-default/

From the docs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-access-control.html "A majority of modern use cases in Amazon S3 no longer require the use of ACLs. We recommend that you keep ACLs disabled, except in unusual circumstances where you need to control access for each object individually. With ACLs disabled, you can use policies to control access to all objects in your bucket, regardless of who uploaded the objects to your bucket."

With that I'd strongly recommend flysystem does not by default add ACLs to the individual PutObject requests (`x-amz-acl`). This may break in various ways as was already described as part of this thread.

**Comment by frankdejonge** [comment] 2023-08-10 13:00
@LarsFronius if only we could set a different default for newly created projects, like AWS can. Unfortunately, that would be a breaking change. I would accept a PR for more documentation for this and recommend frameworks who are more free with BC breaks to adjust their default configuration, but otherwise I'm not going to (in this major version) adjust this default.

**Comment by LarsFronius** [comment] 2023-08-10 14:13
Could there be an option to not set the `x-amz-acl` header on writes? Maybe there already is and I don't know about it.

I think that's all that's needed to at least allow Flysystem to properly interact with the new default settings for AWS S3 buckets. It's not that I ask you to change the default behaviour - it appears that as long as ACLs are disabled on S3 buckets Flysystem can not be configured to work well with them.

**Comment by frankdejonge** [comment] 2023-08-10 14:53
After a report, I've personally tested on my own AWS account the writing a file, this just works. I just created another bucket with default options and wrote a file to it using Flysystem.

Claims like "Flysystem can not be configured to work well with them" without providing any details is not helpful either. You don't put me in a position where I can help you. Please supply information that helps dig into the problem otherwise I cannot help you.

**Comment by Alan01252** [comment] 2023-09-12 09:11
Hi @frankdejonge,

We have the same problem here, purely when accessing the bucket from another AWS account.

Bit of background, we're migrating services from one account to another, we have the same API with the same code base running on both accounts at the moment.

API A running in account A accessing bucket A in account A "just works"
API B running in account B accessing bucket A in account A fails with the error "The bucket does not allow ACLs"

Looking through the code it doesn't look like there's a trivial way to globally disable the ACL, but you can on a per store call basis as per @dswansonvizio comment above

`$results = Storage::disk($this->s3_disk)->put($file_path, file_get_contents($file), ['ACL' => '']);`

Edit: 

I'm an idiot this also works I think

```
       's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_URL'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT'),
            'throw' => true,
            'options' => [
                'ACL' => ''
            ]
        ],
```

**Comment by frankdejonge** [comment] 2023-09-12 09:52
Locking this issue, if you're experiencing this issue, read the comments and solve your problem 👍
