### ISSUE TITLE
Empty file returns contents as false

### ISSUE THREAD

**Issue by paulcanning** [thephpleague/flysystem#627] opened 2016-03-31 14:23 UTC
OK, so this is related to using Flysystem with elFinder and not being able to edit empty (newly created) text files.

When trying to open the file, the contents are returned as false (rather then null or empty?).

I'm fairly certain this issue lies with Flysystem as I tracked the contents back to the `read()` method in Filesystem.php

This method simply returns the contents, and the method that picks it up in elFinder errors out because it is returning false.

Please see here for the issue discussion on elFinder

https://github.com/Studio-42/elFinder/issues/1300

**Comment by PatrickRose** [comment] 2016-03-31 16:35
Reading through your discussion, I think the issue is with the Adapter you're using (the GoogleCloud one) - Flysystem is returning the `contents` returned by the adapter which looks like it might be returning `false`. I'd open an issue there

**Comment by paulcanning** [comment] 2016-04-01 09:06
I'll pass it onto them, see what they say!

**Comment by frankdejonge** [comment] 2016-04-16 14:51
Closing because this was a confirmed bug of a third party adapter.

**Closed by frankdejonge** 2016-04-16 14:51 UTC
