### ISSUE TITLE
Skip unreadable directories

### ISSUE THREAD

**Issue by matbeard** [thephpleague/flysystem#831] opened 2017-08-25 09:22 UTC
Unless I'm missing something (which is quite likely) I can't see a way to configure the Local adapter to skip unreadable folders.

I've temporarily fixed the issue by adding:
`RecursiveIteratorIterator::CATCH_GET_CHILD,` to the `getRecursiveDirectoryIterator` method, but I don't know if there's a more permanent solution?

**Comment by matbeard** [comment] 2017-09-13 12:07
I thought the above 'fix' was working, but it's not. Here's a little more information, in the hope that somebody can help. I'm using Laravel 5.4, in case that makes any differernce.

If the `RecursiveIteratorIterator::CATCH_GET_CHILD` flag is used in the `getRecursiveDirectoryIterator` I don't get any errors if non-readable folders are encountered. However, with this flag set, the `allFiles()` method is not returning any results, even if the folders are readable.

Without this flag set, I get the following error when unreadable folders are encountered:
`RecursiveDirectoryIterator::__construct(C:\path\to\unreadable\folder): An unexpected network error occurred. (code: 59)`

I really need the `allFiles()` method to just give me a list of files and ignore any folders that can't be read.

Is this possible?

**Comment by frankdejonge** [comment] 2017-09-14 14:42
I don't think skipping unreadable directories is a valid option. For reference:

![Everything is fine](https://i.pinimg.com/originals/d0/bb/98/d0bb982540c53ac61eef871d1d2894fb.jpg)

Flysystem is designed around everything being managed within the root, so it requires things to be readable and have correct permissions. Things like network errors seem to me like something that should be fixed rather than ignored. I don't feel anything for implementing this in flysystem because it ads complexity as well as allow very much unexpected behaviour. People don't expect and shouldn't expect failure to be skipped over.

**Comment by matbeard** [comment] 2017-09-14 15:17
I take your point. But just because some folders aren't readable, it doen't mean things aren't configured correctly -- it just means there are some folders you don't have permission to open. I guess I'm going to have to seek an alternative method.

**Comment by frankdejonge** [comment] 2018-05-07 10:03
Took me too long to get back to this, but in those cases you should probably use plain PHP, since it's not a file storage problem, but a system problem. Permissions should be fixed, that can't be done in Flysystem (out of scope).

**Closed by frankdejonge** 2018-05-07 10:03 UTC
