### ISSUE TITLE
AwsS3V3Adapter::writeStream(): external MIME type detection might change the stream cursor position

### ISSUE THREAD

**Issue by bicpi** [thephpleague/flysystem#1790] opened 2024-05-02 11:12 UTC
### Question

When using `AwsS3V3Adapter::writeStream()` and not specifying a content type, the stream resource [is handed over to a dependency of the adapter](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/3.x/AwsS3V3Adapter.php#L158) that is capable of auto-detecting the content type and which implements `League\MimeTypeDetection\MimeTypeDetector`.

It is not guaranteed that the resource passed to the the MIME type detector still has its cursor at the beginning of the stream, i.e. it might not be rewinded.

In my use case, the detector dumps the stream to a file to allow the MIME type detection via a binary that needs a file path. The `writeStream()` then ended up creating a 0 byte empty file.

Should the adapter rewind the stream whenever it was handed out to an external dependency as it cannot know what happens there? Otherwise [the initial rewinding](https://github.com/thephpleague/flysystem/blob/3.x/src/Filesystem.php#L66) cannot be guaranteed.

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.27.0   |
| Adapter Name      | AwsS3V3Adapter |
| Adapter version   | 3.27.0   |

**Comment by frankdejonge** [comment] 2024-05-02 13:14
@bicpi just for clarity, you have a custom mime-type detector implementation that writes the stream to a file, is that correct? If yes, can't it then also rewind the original stream?

**Comment by bicpi** [comment] 2024-05-02 15:20
@frankdejonge Yes, exactly that is what's happening. And we also applied a change to our MIME type detector to rewind. (providing a MIME type via the options is also possible, to completely avoid the detector)

But when using any dependency, should the adapter rely on the external code to do the right thing and in this case rewind? Only the adapter code could guarantee it'll _always_ write the full file as expected - the external code does not know the resource is used by someone else still that expects it to be in a certain state.

I assume this is also why the [initial rewinding](https://github.com/thephpleague/flysystem/blob/3.x/src/Filesystem.php#L66) is done, otherwise it could also rely on the client providing an already rewound resource.

In our case this came really unexpected as the local adapter works fine in development and on S3 all files were empty.

**Comment by frankdejonge** [comment] 2024-05-05 19:03
@bicpi the design of flysystem ensures streams are rewound inside the `writeStream` method, all the other things are setup so they don't consume the stream. If you're consuming the stream your implementation is responsible for the side-effects, not the code around it. So, if you've adapted your detector to rewind the stream, that's the way you should handle it.

**Comment by frankdejonge** [comment] 2024-05-06 19:41
Closing this as this is by design.

**Closed as completed by frankdejonge** 2024-05-06 19:41 UTC

**Comment by bicpi** [comment] 2024-05-07 07:16
@frankdejonge Thx for you answer; I can adapt to that as you describe so all good for my recent issue.

Still, I'd argue that it's not optimal to assume that when passing a mutable variable to an external service, that it will not be changed or that it'll be reset to the initial state. The external service cannot know it has to do this.

**Comment by frankdejonge** [comment] 2024-05-07 14:03
I would argue the other way around, when something mutates state, it's responsible for what it did rather than anything leveraging that piece of logic as a dependency.

**Comment by bicpi** [comment] 2024-05-30 06:06
🤔 Mh, I'd not expect e.g. a `DateTime` object to stay unchanged (or to be reverted to its initial state) after passing it to an (unknown) process. Of course in this case it's easy to just use `DateTimeImmutable` as compared to a file handle.
