### ISSUE TITLE
chmod permission danied

### ISSUE THREAD

**Issue by danielverissimo** [thephpleague/flysystem#566] opened 2015-10-28 23:39 UTC
Hi,

On call "ensureDirectory" this variable "$this->permissionMap" is null:

https://github.com/thephpleague/flysystem/blob/f46f18a62f50d85750798d1d2f57fb04e1cdc707/src/Adapter/Local.php#L95

This variable is assigned in the constructor, because it is still null in the method "ensureDirectory"?

**Comment by twistor** [comment] 2015-10-28 23:49
`permissionMap` is assigned before `ensureDirectory()` is called in the constructor.

https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L72

Are you sure that `permissionMap` is null, and not `permissionMap['dir']['public']`?

**Comment by danielverissimo** [comment] 2015-10-28 23:57
It's really weird, but I put a dd and the result is null:

![screen_shot_2015-10-28_at_21_52_46](https://cloud.githubusercontent.com/assets/7152354/10806679/9dbb7248-7dbe-11e5-8fb4-d1af93c155bb.jpg)

So I changed "$this->permissionMap" to static::$permissions, and works.

**Comment by twistor** [comment] 2015-10-29 00:02
Are you passing `$permissions` into the constructor?

array_replace_recursive() returns null on error.

**Comment by danielverissimo** [comment] 2015-10-29 00:21
But the default $permission construtor parameter is empty [ ], not null, array_replace_recursive() never will be return error in this case.

Even if I pass nothing, the permissionMap shoud be original value.

**Comment by danielverissimo** [comment] 2015-10-29 01:01
@twistor 

I think I found the problem, it is in the class "Cartalyst\Filesystem" and his parent "League\Flysystem\Filesystem":

![screen_shot_2015-10-28_at_22_58_21](https://cloud.githubusercontent.com/assets/7152354/10807498/7aa6c920-7dc7-11e5-9a8b-dcd4cce47c98.jpg)

Executes the write method without first running the Local constructor.

**Comment by frankdejonge** [comment] 2015-12-17 10:31
Since this is caused by an extension of Flysystem I'm closing this issue.

**Closed by frankdejonge** 2015-12-17 10:31 UTC

**Comment by mahmouddev** [comment] 2016-04-05 18:39
@danielverissimo 
kindly, can you describe how do you fix this issue , i have the same scenario !!

**Comment by danielverissimo** [comment] 2016-04-05 21:32
Hi @mahmouddev, this is a bug on Cartalyst\Filesystem version 3.0.3, try update cartalyst.
