### ISSUE TITLE
FTP adapter bug: $filesystem->has() returns false 

### ISSUE THREAD

**Issue by tristanbes** [thephpleague/flysystem#539] opened 2015-08-10 10:18 UTC
Hi,

My PHP script does

1. List content of FTP
2. Downloads all images from the FTP
3. Delete sucessfully downloaded images

For the 1, I use `$filesystem->listContents()` which gives me the list of all file i'll have to download.
Then for the 2, I do inside a loop 
```php
 foreach ($items as $i => $item) {
        if (!$filesystem->has($item['path'])) {
            $this->logger->error('[ImportPhotoCommand] tried to import not-existant photo in the eyes of flysystem: '. $item['path']);
            continue;
        }

        $contents = $filesystem->read($item['path']);
} 
``` 

At the 25th/724 image, minute 2:27 on script execution time, I get 17 new entries in my error log containing `tried to import not-existant photo in the eyes of flysystem`, then It stopps the script with the "all photos imported" log.

More important, the files are not deleted, (they are also in a check if flysystem `has` the file, then `delete` it).

The files are correctly named, and does not have spaces or exotique characters.

SSL is off, I'm connecting as the same user that uploads the file.
I first thought it was a timeout problem, so I put 7200sec as a timeout, but it didn't work. 
I'm using `v1.0.11`

**Comment by tristanbes** [comment] 2015-08-10 12:31
Changing to amazon fixed the issue. So there is really a problem with either the FTP (it's a FTP from ovh.com), either the library itself.

**Comment by frankdejonge** [comment] 2015-08-11 06:53
@tristanbes hi, do you have more information why it was failing? Do you know the type of ftp server? Perhaps it was FTPD?

**Comment by tristanbes** [comment] 2015-08-11 08:26
I don't know more details. I do not own the FTP server. But it's widely used in France since OVH is the biggest european hoster. Why is there no reconnexion mecanism inside flysystem ? Check if the connexion is opened, then do the command, if the connexion has been closed, try reconnect. I guess that would solve the problem.

**Comment by frankdejonge** [comment] 2015-08-13 14:06
@tristanbes with no further information I really don't have any leads to go by here. If you have more information, please supply it, otherwise I have no other option but to close this issue.

**Comment by tristanbes** [comment] 2015-08-13 14:08
I understand, but again I think that any reconnexion mecanism that would implement flysystem for the FTP adapter would kill this issue.

I remember that this happened to other too in the closed/open issue of this repo. My 2 cents ;-)

**Comment by frankdejonge** [comment] 2015-09-20 11:51
@tristanbes I just saw another issue which had similar problems, though slightly different, which probably was caused by not having the connection in passive mode. This could be another thing that could solve the issue.

**Comment by frankdejonge** [comment] 2015-09-20 20:29
@tristanbes re-connection has been added. Closing this issue.

**Closed by frankdejonge** 2015-09-20 20:29 UTC
