### ISSUE TITLE
FTP Adapter sporadically fails on call to has()

### ISSUE THREAD

**Issue by stevenmusumeche** [thephpleague/flysystem#421] opened 2015-02-12 17:28 UTC
Sometimes this works, sometimes it doesn't.  I am able to connect to the FTP server manually with no errors.
```
$fileName = 'fileonserver.txt';
if ($this->filesystem->has($fileName)) {
    //whatever
}
````
I get the following PHP error:

`Notice: Undefined offset: 8`

I've run it through xdebug and this is the line that throws the Notice.

**Comment by stevenmusumeche** [comment] 2015-02-12 17:32
This appears to be an error on line 259 of AbstractFtpAdapter

**Comment by frankdejonge** [comment] 2015-02-12 20:59
@stevenmusumeche what kind of FTP server is this?

**Comment by stevenmusumeche** [comment] 2015-02-12 21:41
I don't know, it is not a server that I have control over.

**Comment by frankdejonge** [comment] 2015-02-27 12:06
Since you mentioned this sometimes happens I can only assume this is an unstable FTP server. There's not really a way for flysystem to take this into account.

**Comment by stevenmusumeche** [comment] 2015-02-27 14:34
After further testing, it is not sporadic.  It consistently fails in the same way.  Is there some debugging information I can give you to reproduce the error?

**Comment by frankdejonge** [comment] 2015-02-27 14:35
The output of `ftp_systype` would be handy.

**Comment by frankdejonge** [comment] 2015-03-21 19:58
@stevenmusumeche got more info on this? I assume this is probably a network thing and/or an unstable server? Since there's been no other response I'm closing this issue. If there are new leads on why this is something that relates flysystem to the cause, pleaase comment and I'll re-open the issue.

**Closed by frankdejonge** 2015-03-21 19:58 UTC
Labels: needs more input

**Comment by brainless81** [comment] 2017-07-05 09:06
Maybe #809 could cause your ftp server to close down the connection?
