### ISSUE TITLE
FTP adapter - allowing searches using wildcard

### ISSUE THREAD

**Issue by JonasHaouzi** [thephpleague/flysystem#667] opened 2016-06-06 17:15 UTC
Hi guys.

First of all, thanks for the amazing work you're doing, I really appreciate it.
I'm reporting here a little issue I was faced to.
## The issue

Using the **FTP adapter**, I wanted to list the files matching a given pattern which **contains wildcards**.
I currently do it with the **adapter of Amazon S3**, but I was surprise to see it was no working for FTP.

Therefore, I dug and realised this was the expected behaviour by the adapter since [you're protecting the wildcard](https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Ftp.php#L451).
## How I fix it?

For the moment, I created a custom FTP adapter on top of yours.
You can find it here: https://github.com/Viscaweb/EasyBackups/blob/master/src/Adapter/FTPWildCardSearchAdapter.php

Basically, I'm re-implementing the three following methods:
1. **__construct →** now accepts a new config. option: **allowSearchingUsingWildCard**
2. **listDirectoryContents →** if this option is true, I stop protecting it.
3. **normalizeListing →** since _ftp_rawlist_ already includes the full path when requesting files using wildcards, I apply the code adding the prefix only if the user asked for a path not containing wildcard.
## My proposal

I think we should allow searching the files by patterns for the FTP adapter, as we do for others adapters such as the one for Amazon S3. However and for backward compatibility, the user must specify it explicitly.
Therefore, I'd suggest either to add a new parameter in the **listContent()** implementation to allow searching by pattern, or adding a new option (as I do in my implementation) when instancing the adapter.

Let me know your thoughts, I'm willing to create a pull request with a proper implementation if we agree on the way to do.

Thanks.

**Comment by barryvdh** [comment] 2016-06-06 18:13
duplicate of https://github.com/thephpleague/flysystem/issues/503

**Comment by JonasHaouzi** [comment] 2016-06-06 18:17
Oh, I haven't see it.

Thanks 👍

**Closed** 2017-02-18 00:00 UTC
