### ISSUE TITLE
AbstractFtpAdapter: Undefined offset: 8

### ISSUE THREAD

**Issue by sebastianblum** [thephpleague/flysystem#626] opened 2016-03-30 09:55 UTC
Hello!

We are using the FTP-Adapter and if we check with $filesystem->has($path) if a file exists, we get this stack trace for not existing files:

Undefined offset: 8

/.../vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:71
/.../vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php:398
/.../vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php:379
/.../vendor/league/flysystem/src/Adapter/Ftp.php:350
/.../vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php:525
/.../vendor/league/flysystem/src/Filesystem.php:54

Here is the problem: https://github.com/thephpleague/flysystem/blob/master/src/Adapter/AbstractFtpAdapter.php#L398

**Comment by barryvdh** [comment] 2016-03-30 10:41
Duplicate of #613 ?

**Comment by frankdejonge** [comment] 2016-06-07 20:54
This was fixed in a PR.

**Closed by frankdejonge** 2016-06-07 20:54 UTC
